### ISSUE TITLE
Update for v1.4?

### ISSUE THREAD

**Issue by Nisto** [nu774/foo_input_caf#2]
Hi. Can you please update this component for v1.4 so that the decoder priority order can be changed?

**Comment by nu774** [comment]
Done.

**Comment by Nisto** [comment]
Thank you!

**Comment by sergeevabc** [comment]
Foobar2000  2+ requires x64 version of this plugin. If possible, please update.

**Comment by nu774** [comment]
Now published 0.4.0 with x64 support.
